In [ ]:
# numpy数组创建的方式


In [8]:
import numpy as np
from numpy.ma.core import shape

l = [1,2,3,4,5]
arr = np.array(l)
arr[[1,2]] # numpy取出多个数据直接通过对应的数组下标获取

array([2, 3])

In [17]:
con = arr >= 3 #取出大于3的数据
print(con) #把大于等于3的数条件进行筛选
arr[con]

[False False  True  True  True]


array([3, 4, 5])

In [22]:
# arr的不同的创建方式
np.ones(shape=10)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
np.zeros(shape=10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.full(shape=10,fill_value=3.14)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [24]:
np.random.randint(low=0,high=10,size=10)

array([0, 9, 0, 0, 1, 7, 2, 5, 9, 7])

In [31]:
np.random.randn(10) #正太分布 平均值0 标准差1

array([-0.98278957, -0.94120442, -1.48655712,  1.49862247, -0.31417352,
        0.28229512,  0.11584674,  0.53908877,  0.85498834, -0.17594301])

In [34]:
np.linspace(1,99,50) #等差数列

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23., 25.,
       27., 29., 31., 33., 35., 37., 39., 41., 43., 45., 47., 49., 51.,
       53., 55., 57., 59., 61., 63., 65., 67., 69., 71., 73., 75., 77.,
       79., 81., 83., 85., 87., 89., 91., 93., 95., 97., 99.])

In [112]:
# 等比数列
np.set_printoptions(suppress=True) #不显示科学技术发
np.logspace(0,10,base=2,num=11)


array([   1.,    2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,
        512., 1024.])

In [51]:
np.random.randint(low=0,high=10,size=(3,4)) #二维数组

array([[2, 4, 2, 3],
       [3, 2, 7, 9],
       [2, 5, 0, 3]])

In [50]:
np.random.randint(low=0,high=10,size=(3,4,5)) #三维数组

array([[[6, 5, 4, 3, 9],
        [7, 5, 1, 3, 9],
        [9, 1, 2, 8, 9],
        [3, 5, 6, 5, 4]],

       [[0, 5, 5, 6, 7],
        [8, 6, 1, 9, 8],
        [4, 9, 8, 0, 8],
        [7, 1, 2, 0, 2]],

       [[3, 1, 9, 6, 8],
        [3, 9, 5, 9, 7],
        [9, 2, 5, 9, 5],
        [4, 4, 0, 4, 5]]])

In [2]:
import numpy as np
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
import numpy as np
arr = np.random.random(size=(3,5))
arr.shape #数组的维度


(3, 5)

In [10]:
arr.dtype #数据类型

dtype('float64')

In [9]:
arr.ndim #纬度

2

# 数据查看

In [14]:
print(arr.size) #元素个数
print(arr.itemsize) #每个元素的大小

15
8


In [23]:
bb = [i for i in range(0,10,3)]
print(bb)
arr = np.arange(0,10,3) #创建一个数组等差数列

print(arr)
np.save('./data1',arr)

[0, 3, 6, 9]
[0 3 6 9]


In [27]:
arr2 = np.load('./data1.npy')
print(arr2)

[0 3 6 9]


In [30]:
np.set_printoptions(suppress=True)
arr2 = np.logspace(0,10,base=2,num=11)
arr2

array([   1.,    2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,
        512., 1024.])

In [31]:
np.savez('./data2.npz',arr1=arr,arr2=arr2) # 保存多个数组

In [36]:

np.load('./data2.npz')['arr1'] #取其中一个数组

array([   1.,    2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,
        512., 1024.])

In [ ]:
np.load('./data2.npz')['arr2'] #取另外一个数组

# 数据类型

In [37]:
np.array([1,2,3,4,5],dtype=np.int16)

array([1, 2, 3, 4, 5], dtype=int16)

In [39]:
np.array([1,2,3,4,5],dtype=np.int32)


array([1, 2, 3, 4, 5], dtype=int32)

In [43]:
arr = np.random.randint(low=0,high=100,size=(100,50,30),dtype=np.int8)
np.save('./data3.npy',arr)

In [44]:
arr1 = np.random.randint(low=0,high=100,size=(100,50,30),dtype=np.int64)
np.save('./data4.npy',arr1)

In [46]:
# unit8 无符号的256 0-255
arr2 = np.random.randint(low=0,high=100,size=(100,50,30),dtype=np.uint8)
arr2

array([[[11, 91, 33, ..., 56, 70, 69],
        [64, 66, 21, ..., 26, 33, 80],
        [43, 51, 71, ..., 64, 35, 85],
        ...,
        [95, 23, 20, ..., 63, 48,  6],
        [19, 94, 87, ..., 14, 36, 59],
        [89, 15, 86, ..., 29, 37, 32]],

       [[37, 79, 49, ..., 66, 90, 26],
        [78, 13, 40, ..., 62, 60, 76],
        [60, 62, 24, ..., 47, 55, 14],
        ...,
        [99, 69, 14, ..., 41,  8, 79],
        [32, 30, 85, ..., 51, 18, 69],
        [ 3, 57, 89, ..., 48, 99, 27]],

       [[33, 32, 61, ..., 87, 38, 48],
        [82, 10, 54, ..., 87, 20, 43],
        [85, 17, 69, ..., 68, 32, 44],
        ...,
        [76, 42, 25, ..., 77, 69, 10],
        [39, 48, 24, ..., 64, 65,  5],
        [68, 29, 63, ...,  5, 63, 18]],

       ...,

       [[16, 58, 74, ..., 26, 30, 26],
        [23, 60, 55, ...,  9, 99, 58],
        [77, 17, 12, ..., 19, 81, 25],
        ...,
        [59, 37, 18, ..., 81, 20,  4],
        [72, 41,  0, ..., 61,  3, 57],
        [34, 64, 55, ..., 20, 72

In [52]:
np.arange(0,128,dtype=np.uint8)
np.arange(-128,128,dtype=np.int8)

array([-128, -127, -126, -125, -124, -123, -122, -121, -120, -119, -118,
       -117, -116, -115, -114, -113, -112, -111, -110, -109, -108, -107,
       -106, -105, -104, -103, -102, -101, -100,  -99,  -98,  -97,  -96,
        -95,  -94,  -93,  -92,  -91,  -90,  -89,  -88,  -87,  -86,  -85,
        -84,  -83,  -82,  -81,  -80,  -79,  -78,  -77,  -76,  -75,  -74,
        -73,  -72,  -71,  -70,  -69,  -68,  -67,  -66,  -65,  -64,  -63,
        -62,  -61,  -60,  -59,  -58,  -57,  -56,  -55,  -54,  -53,  -52,
        -51,  -50,  -49,  -48,  -47,  -46,  -45,  -44,  -43,  -42,  -41,
        -40,  -39,  -38,  -37,  -36,  -35,  -34,  -33,  -32,  -31,  -30,
        -29,  -28,  -27,  -26,  -25,  -24,  -23,  -22,  -21,  -20,  -19,
        -18,  -17,  -16,  -15,  -14,  -13,  -12,  -11,  -10,   -9,   -8,
         -7,   -6,   -5,   -4,   -3,   -2,   -1,    0,    1,    2,    3,
          4,    5,    6,    7,    8,    9,   10,   11,   12,   13,   14,
         15,   16,   17,   18,   19,   20,   21,   

In [53]:
# 数据类型转化
arr1.astype(np.int16) #转化数据类型

array([[[59, 52, 72, ..., 75, 51, 31],
        [37, 76, 95, ..., 93, 18, 11],
        [ 4, 46, 87, ..., 39, 32,  8],
        ...,
        [73, 17, 74, ..., 80, 75, 57],
        [61, 33, 51, ..., 57, 54, 78],
        [32, 65,  1, ...,  5,  0, 25]],

       [[15, 38, 85, ..., 82, 26, 61],
        [55, 59,  0, ..., 23, 85, 34],
        [53, 56, 50, ..., 54,  1, 46],
        ...,
        [37, 64, 10, ..., 85, 91, 89],
        [75, 73, 45, ..., 99, 98, 31],
        [82, 65, 37, ..., 51,  5, 27]],

       [[ 1, 52, 24, ..., 21, 29,  3],
        [74, 27, 42, ..., 62, 91, 42],
        [99, 53, 55, ...,  3, 83, 58],
        ...,
        [28, 24,  4, ..., 19, 69,  6],
        [47, 96,  6, ..., 63, 27, 83],
        [63, 47, 78, ..., 29, 92, 56]],

       ...,

       [[21, 76, 32, ..., 84, 11,  3],
        [83, 50, 85, ..., 73, 27, 95],
        [46, 65, 21, ..., 14,  4, 20],
        ...,
        [25, 44, 31, ..., 16,  4, 24],
        [60,  7, 60, ..., 72, 53, 61],
        [17, 39, 94, ..., 30, 90

In [54]:
arr1.astype(np.float32)

array([[[59., 52., 72., ..., 75., 51., 31.],
        [37., 76., 95., ..., 93., 18., 11.],
        [ 4., 46., 87., ..., 39., 32.,  8.],
        ...,
        [73., 17., 74., ..., 80., 75., 57.],
        [61., 33., 51., ..., 57., 54., 78.],
        [32., 65.,  1., ...,  5.,  0., 25.]],

       [[15., 38., 85., ..., 82., 26., 61.],
        [55., 59.,  0., ..., 23., 85., 34.],
        [53., 56., 50., ..., 54.,  1., 46.],
        ...,
        [37., 64., 10., ..., 85., 91., 89.],
        [75., 73., 45., ..., 99., 98., 31.],
        [82., 65., 37., ..., 51.,  5., 27.]],

       [[ 1., 52., 24., ..., 21., 29.,  3.],
        [74., 27., 42., ..., 62., 91., 42.],
        [99., 53., 55., ...,  3., 83., 58.],
        ...,
        [28., 24.,  4., ..., 19., 69.,  6.],
        [47., 96.,  6., ..., 63., 27., 83.],
        [63., 47., 78., ..., 29., 92., 56.]],

       ...,

       [[21., 76., 32., ..., 84., 11.,  3.],
        [83., 50., 85., ..., 73., 27., 95.],
        [46., 65., 21., ..., 14.,  4., 20.

# 数据的运算

In [57]:
nd = np.random.randint(low=0,high=100,size=(100,30),dtype=np.int8)

In [58]:
nd ** 2

array([[ -92,    0,   68, ...,  -92,    4,  -15],
       [  36,   97,   16, ..., -103,  100,   97],
       [ -31,  -39,  -79, ...,   65,   97,  -31],
       ...,
       [  64, -127,   36, ...,    1,  -15,   36],
       [  16,  -60,  -15, ..., -112, -112,    0],
       [  -7,   16,   97, ...,  -79,    9,   65]],
      shape=(100, 30), dtype=int8)

In [ ]:
nd / 2

In [61]:
nd + 2

array([[28, 34, 20, ..., 92,  4, 91],
       [72, 81, 62, ..., 61, 12, 51],
       [17, 29, 59, ..., 97, 81, 17],
       ...,
       [26, 65,  8, ...,  3, 91, 72],
       [70, 80, 91, ..., 54, 22, 18],
       [55, 38, 81, ..., 59,  5, 97]], shape=(100, 30), dtype=int8)

In [62]:
nd % 2

array([[0, 0, 0, ..., 0, 0, 1],
       [0, 1, 0, ..., 1, 0, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [0, 1, 0, ..., 1, 1, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [1, 0, 1, ..., 1, 1, 1]], shape=(100, 30), dtype=int8)

In [63]:
nd // 2

array([[13, 16,  9, ..., 45,  1, 44],
       [35, 39, 30, ..., 29,  5, 24],
       [ 7, 13, 28, ..., 47, 39,  7],
       ...,
       [12, 31,  3, ...,  0, 44, 35],
       [34, 39, 44, ..., 26, 10,  8],
       [26, 18, 39, ..., 28,  1, 47]], shape=(100, 30), dtype=int8)

In [ ]:
nd > 50

In [ ]:
nd < 50

In [ ]:
nd >= 50

In [ ]:
nd <= 50

In [ ]:
nd == 50

In [ ]:
nd != 50

In [ ]:
nd & 50

In [ ]:
nd | 50

In [ ]:
nd ^ 50

In [ ]:
nd & 50 | 50

In [64]:
nd & 50^ 50

array([[32, 18, 32, ..., 32, 48, 34],
       [48, 48,  2, ...,  0, 48,  2],
       [48, 32,  2, ..., 32, 48, 48],
       ...,
       [34,  0, 48, ..., 50, 34, 48],
       [50, 48, 34, ...,  2, 34, 34],
       [ 2, 18, 48, ...,  2, 48, 32]], shape=(100, 30), dtype=int8)

In [70]:
# 如果使用+= -= *=  会讲原来的数据覆盖
nd += 50
nd -= 50
nd *= 50
nd //= 50

# 赋值和视图

In [72]:
nd2 = nd.copy()

In [74]:
nd3 = np.arange(0,100,dtype=np.int8)

nd3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
      dtype=int8)

In [75]:
nd3 -= 10


In [78]:
nd3 = nd3.view()
nd3

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,
        16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
        29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
        42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,
        55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,
        68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,
        81,  82,  83,  84,  85,  86,  87,  88,  89], dtype=int8)

# 索引和切片

In [86]:
arr = np.random.randint(low=0,high=100,size=100,dtype=np.int8)
arr

array([12,  7, 63,  2,  9, 37, 49, 27, 82, 31, 35, 68, 69, 82, 16, 68, 28,
       29, 62, 48, 14, 20,  0, 71, 23, 17, 27, 63, 44, 16, 17, 15, 25, 31,
       99, 14, 46, 75, 96, 38, 21, 73, 39, 19, 60, 34, 78, 37, 76, 56, 31,
       40, 80, 82, 87, 51, 62, 99, 36, 24,  5, 98, 44, 64,  9, 22, 17, 36,
       29, 36, 97, 60, 47, 91,  8, 36, 80, 60, 63, 55, 73, 26, 45, 22, 49,
       85, 64, 22, 22, 22, 41, 89, 74, 84, 24, 46,  7, 48, 11, 47],
      dtype=int8)

In [87]:
arr[[0,3,5]] #索引

array([12,  2, 37], dtype=int8)

In [88]:
arr[3:6] #切片

array([ 2,  9, 37], dtype=int8)

In [89]:
arr[3:6:2] #步长为2

array([ 2, 37], dtype=int8)

In [92]:
arr[::3] #步长为3

array([12,  2, 49, 31, 69, 68, 62, 20, 23, 63, 17, 31, 46, 38, 39, 34, 76,
       40, 87, 99,  5, 64, 17, 36, 47, 36, 63, 26, 49, 22, 41, 84,  7, 47],
      dtype=int8)

In [93]:
arr[::-2] #倒序

array([47, 48, 46, 84, 89, 22, 22, 85, 22, 26, 55, 60, 36, 91, 60, 36, 36,
       22, 64, 98, 24, 99, 51, 82, 40, 56, 37, 34, 19, 73, 38, 75, 14, 31,
       15, 16, 63, 17, 71, 20, 48, 29, 68, 82, 68, 31, 27, 37,  2,  7],
      dtype=int8)

## 二维数据的索引和切片


In [97]:
arr2 = np.random.randint(low=0,high=100,size=(3,5),dtype=np.int8)
arr2[0,2]


np.int8(7)

In [98]:
arr2[1,[1,2]] #获取第二行 第三列的数据

array([90, 56], dtype=int8)

In [100]:
arr2[[1,2],3:]  #索引和切片配合使用

array([[69, 98],
       [ 8, 90]], dtype=int8)

# 花式索引

In [101]:
arr = np.random.randint(low=0,high=100,size=20)
arr

array([14, 30, 25, 65, 69, 66, 63, 40, 40,  3, 63, 79, 30, 70, 15, 80,  6,
       77, 25,  0])

In [102]:
arr[[3,5,7]]

array([65, 66, 40])

In [103]:
conn = arr >60
arr[conn]

array([65, 69, 66, 63, 63, 79, 70, 80, 77])

In [110]:
# 取出小于30 大于80 的数据
con1 = arr <30
con2 = arr >70
cond1 = con1 | con2 # numpy的 | 相当于or运算
cond2 = con1 & con2 # numpy的 &相当于and 运算
arr[cond1]

array([14, 25,  3, 79, 15, 80,  6, 77, 25,  0])

In [111]:
arr[cond2]


array([], dtype=int64)