# 作业

1、创建一个长度为10的一维全为0的ndarray对象，然后让第5个元素等于1

2、创建一个元素为从10到49的ndarray对象，间隔是1

3、将第2题的所有元素位置反转

4、使用np.random.random创建一个10*10的ndarray对象，并打印出最大最小元素

5、创建一个10*10的ndarray对象，且矩阵边界全为1，里面全为0

6、创建一个每一行都是从0到4的5*5矩阵

7、创建一个范围在(0,1)之间的长度为12的等差数列，创建[1,    2,    4,    8,   16,   32,   64,  128,  256,  512, 1024]等比数列。

8、创建一个长度为10的正太分布数组np.random.randn并排序

9、创建一个长度为10的随机数组并将最大值替换为-100

10、如何根据第3列大小顺序来对一个5*5矩阵排序？


In [2]:
#1、创建一个长度为10的一维全为0的ndarray对象，然后让第5个元素等于1
import numpy as np
arr = np.full(10,0)
arr[4] = 1
arr

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [8]:
# 2、创建一个元素为从10到49的ndarray对象，间隔是1
arr = np.arange(10,50,1)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [9]:
# 3、将第2题的所有元素位置反转
arr[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [17]:
# 4、使用np.random.random创建一个10*10的ndarray对象，并打印出最大最小元素
arr = np.random.random((10,10))
print(arr.max())
print(arr.min())

0.9954665944823993
0.000618998003475979


In [62]:
import numpy as np
# 5、创建一个10 * 10的ndarray对象，且矩阵边界全为1，里面全为0
arr = np.zeros((10,10))
# 6、创建一个每一行都是从0到4的5 * 5
arr[0:-1,[0,-1]] = 1
# 矩阵
#
# 7、创建一个范围在(0, 1)
# 之间的长度为12的等差数列，创建[1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]
# 等比数列。
np.set_printoptions(suppress=True)
arr = np.logspace(0,10,base=2,num=11)
arr
#
# 8、创建一个长度为10的正太分布数组np.random.randn并排序
#

# 9、创建一个长度为10的随机数组并将最大值替换为 - 100
#
arr = np.random.randint(0,100,10)
arr1 = np.random.random(100)
print(arr1)
print(arr.max())
arr[arr.argmax()] = 100
arr
# 10、如何根据第3列大小顺序来对一个5 * 5 矩阵排序？
arr = np.random.randint(0,100,(5,5))
print(arr)
arr = arr[arr[:,2].argsort()]
arr


[0.4 0.9 1.  0.8 0.4 0.5 0.9 0.2 0.2 0.7 0.6 0.3 0.4 0.  0.2 0.9 0.  0.5
 0.7 0.8 0.8 0.9 0.7 0.9 0.9 0.6 0.5 0.6 0.2 0.4 0.8 0.2 0.1 1.  0.2 0.8
 0.5 0.8 0.8 0.2 0.8 0.4 0.2 0.4 0.8 0.7 0.4 0.5 0.7 0.  0.5 0.2 0.9 0.6
 0.1 1.  0.9 0.4 0.4 0.5 0.5 0.  0.4 0.2 0.5 0.5 0.6 0.7 0.9 0.5 0.7 0.3
 0.8 0.3 0.9 0.6 0.3 0.1 0.8 0.6 0.7 0.5 0.2 0.3 0.8 0.7 0.1 0.3 0.3 0.
 0.7 0.1 0.9 0.6 1.  1.  0.9 0.9 0.5 0.1]
91
[[65 20 31 16 76]
 [67 17 91 12 91]
 [21 29  7 57 74]
 [51 94 75 72 70]
 [28 78 96 66 55]]


array([[21, 29,  7, 57, 74],
       [65, 20, 31, 16, 76],
       [51, 94, 75, 72, 70],
       [67, 17, 91, 12, 91],
       [28, 78, 96, 66, 55]])